spring:
  application:
    name: service-provider
  cloud:
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ['*', 'service-registry']